name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [ ]  # set to ["build"] if you keep both jobs in one workflow file
    steps:
      - uses: actions/checkout@v4

      # (Optional) Generate changelog via Conventional Commits
      # - uses: googleapis/release-please-action@v4
      #   with: ...
      # If you prefer a quick native notes:
      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const tag = context.ref.replace('refs/tags/','');
            const r = await github.rest.repos.generateReleaseNotes({ owner, repo, tag_name: tag });
            core.setOutput('body', r.data.body);

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.body }}
          draft: false
          prerelease: false
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
